apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: default
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://piyushh69:Gonegirl%408090@cluster0.lmon3le.mongodb.net/auction_db?retryWrites=true&w=majority&appName=Cluster0"
  JWT_SECRET_KEY: "bb64936b0b6d10eed051bb85a0a4f4c0f88c02a8494f125c407d6e95bb5557264a87f873c4fe4f0fbd313a261a4d8c261add94b1679bbb3cc633a2dbc587e073"
  CLOUDINARY_API_KEY: "955396981985649"
  CLOUDINARY_API_SECRET: "BuDrxZWAF4hhzUJFOu3wpJVk0nE"
  SMTP_PASSWORD: "azqbfvibfstaztdr"
