apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: default
data:
  PORT: "5000"
  COOKIE_EXPIRE: "7"
  JWT_EXPIRE: "7d"
  FRONTEND_URL: "https://piyush-web-app.co.in"
  VITE_BACKEND_URL: "https://piyush-web-app.co.in"
  CLOUDINARY_CLOUD_NAME: "ddr6ms1jg"
  SMTP_SERVICE: "gmail"
  SMTP_PORT: "465"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_MAIL: "shrivastavavector@gmail.com"
