apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  labels:
    app.kubernetes.io/instance: mern-app
data:
  FRONTEND_URL: http://34.55.167.131
  BACKEND_URL:  http://34.58.87.15
  PORT: "5000"

